### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by linziyang1106** [linziyang1106/2022#1]

**Comment by linziyang1106** [comment]
- [ ] 利用ios快捷指令记录每日起床时间

**Comment by linziyang1106** [comment]
- [ ] 完成《区块链和交通》

**Comment by linziyang1106** [comment]
- [ ] 文件系统水印透明度问题
- [ ] merge代码问题（不使用reset的情况）
- [ ] 业务判断问题（更新，同名……）

**Comment by linziyang1106** [comment]
- [ ] 优化Action
- [ ] 看研报
- [ ] 完成《区块链和交通》

**Comment by linziyang1106** [comment]
- [ ] 文件系统开发 文件编辑 剪切复制操作
- [ ] kafka connect jms 插件 支持rabbitmq

**Comment by linziyang1106** [comment]
- [ ] kafka connect支持rabbitmq

**Comment by linziyang1106** [comment]
- [ ] 文件系统新需求处理
- [ ] 人员管理缺陷修复
- [ ] 述职ppt上传需求梳理 设计

**Comment by linziyang1106** [comment]
- [ ] 述职ppt设计，需求确认

**Comment by linziyang1106** [comment]
- [ ] 述职ppt测试

阅读：
- [ ] 《延续香火的理想与普遍绝嗣的现实——基于家谱的人口数据》
- [ ] 《波卡平行链设计理念与运作机制》

直播：
- [ ] 链上地址分析
- [ ] Moonbeam & Polkadot

**Comment by linziyang1106** [comment]
- [ ] 周记
- [ ] 收纳

**Comment by linziyang1106** [comment]
- [ ] 员工中心 员工excel导入
- [ ] kafka connect jms rabbitmq插件
- [ ] 数据中台缺陷

**Comment by linziyang1106** [comment]
- [ ] 文件系统支持视频预览、markdown在线预览
- [ ] 文件系统 首页速度偏慢 [^1]
- [ ] 根目录选取问题 [^2]
- [ ] kafka connect rabbitmq插件

[^1]: 需要考虑后续文件量变大的问题，分页效率等问题
[^2]: 需要考虑后续系统移植问题（库id问题）

**Comment by linziyang1106** [comment]
- [ ] kafka connect rabbit 插件 使用中台方式接入
- [ ] markdown预览

**Comment by linziyang1106** [comment]
- [ ] 搬家 
- [ ] 周记

**Comment by linziyang1106** [comment]
- [ ] 文件普通员工不可下载

**Comment by linziyang1106** [comment]
- [ ] 利用scroll查询es数据

**Comment by linziyang1106** [comment]
- [ ] 开一个Solidity12天学习计划
- [ ] 目标管理卡

**Comment by linziyang1106** [comment]
今天开始隔离了，2022CCP的第一记铁拳狠狠地打过来了，不过有了更多的时间可以专注
- [ ] Solidity学习

**Comment by linziyang1106** [comment]
- [ ] clearai海外站

**Comment by linziyang1106** [comment]
- [ ] 柱状图查询优化（大数据量）

**Comment by linziyang1106** [comment]
#### 测试markdown折叠内容
<details>
  <summary>点击展开!</summary>
  
  ## Heading
- [ ] 1. 柱状图优化(使用es的histogram aggregation)
- [ ] 2. 解决海宁项目算法中台启动问题
</details>

**Comment by linziyang1106** [comment]
- [ ] [Benthos](https://www.benthos.dev/)文档

**Comment by linziyang1106** [comment]
- [ ] 算法容器erueka版本镜像

**Comment by linziyang1106** [comment]
- [ ] 算法容器、算法包bean扫描路径问题
        - 启动类取消springboot启动注解
        - 包名，第三级不能是its
- [ ] 海宁项目公司环境安装kafka-connect
       - ymal文件可以是不用添加clusterIp

**Comment by linziyang1106** [comment]
- [ ] 转换包开发文档
- [ ] 数据中台部署文档

**Comment by linziyang1106** [comment]
- [ ] 搜索引擎收录域名

**Comment by linziyang1106** [comment]
尝试番茄钟

今日工作
- [ ] template
- [ ] template

临时急迫事项
- [ ] template
- [ ] template

事项盘点
- [ ] template
- [ ] template

**Comment by linziyang1106** [comment]
今日工作
- [ ] template
- [ ] template

临时急迫事项
- [ ] template
- [ ] template

事项盘点
- [ ] template
- [ ] template

**Comment by linziyang1106** [comment]
今日工作
- [ ] 链路日志无法发送的问题
- [ ] 整理部署问题
- [ ] vuepress部署

临时急迫事项


事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] 整理文档-kafka-connect 🍅🍅🍅🍅
- [ ] 数据链路监控方案预研  🍅🍅🍅🍅🍅🍅


临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] 优化文档README，改为提交PR的模式
- [ ] 链路监控方案

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] 给在线文档配置Jenkins，看看能否解决pandoc的问题
- [ ] 链路原型图
- [ ] 文档不全（数据中台）

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 文档目录结构处理。
- [ ] 转移智慧交通OS1.8文档

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 制定一下Solidity的计划
- [x] 优化文档

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 制定一下Solidity的计划，公开

临时急迫事项

事项盘点

想做：
- [ ] 蒸鱼
- [ ] 红烧肉
- [ ] 蚝油生菜
- [ ] 小米南瓜粥

买啥：
- [ ] 鲈鱼 或 梅鱼
- [ ] 蒸鱼豉油
- [ ] 生菜
- [ ] 小米
- [ ] 大米
- [ ] 南瓜
- [ ] 糖、盐、椒盐
- [ ] 水饺
- [ ] 酸奶

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 了解零知识证明
- [ ] 测试upms rpc接口
- [ ] 学习开源的数据中台

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 员工中心try catch
- [ ] 学习开源的数据中台

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] Feign 传输response

临时急迫事项

事项盘点
- [ ] 超市 - 鸡腿/番茄/鸡蛋面/生菜

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] Feign 传输response
- [ ] 算法中台文档修改，exports拼写问题，k8s的配置缺失
- [ ] 算法中台yaml抽离

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] upms 问题排查（1. `connection reset peer by peer`, 2. `Unknown column 'REQUESTRESOURCE'`）
- [ ] 批量下载，zip包

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 设计数据中台docker镜像上传

临时急迫事项

事项盘点

**为了使在线文档的导出更为优雅**
- [ ] markdown转pdf latex模板 [少数派](https://sspai.com/post/47110)

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 镜像上传任务拆解，分配
- [ ] 链路详情页 指标修改
- [ ] 链路日志 kafka作为输入源的日志

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 创建链路指定镜像设计

临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 员工中心全局搜索
- [ ] 预览 apose去除水印
- [ ] 镜像上传前端对接

临时急迫事项


事项盘点

**Comment by linziyang1106** [comment]
- [ ] 文件预览太大 oom

**Comment by linziyang1106** [comment]
超市
- [ ] 酸奶
- [ ] 鸡腿
- [ ] 小米辣、葱
- [ ] 鸡蛋
- [ ] 零食

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 文件收藏 新增设置文件收藏
- [ ] 大脑 数据中台接口


临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 镜像上传前端检查
- [ ] 员工中心upms问题排查，58环境复现


临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
今日工作
- [ ] **早点睡**、**早点睡**、**早点睡**
- [ ] 员工中心内存溢出排查
- [ ] 数据源文档更新
- [ ] 镜像上传前端


临时急迫事项

事项盘点

**Comment by linziyang1106** [comment]
- [ ] 修改预览接口

**Comment by linziyang1106** [comment]
- [ ] 网站更新

**Comment by linziyang1106** [comment]
- [ ] 周报
- [ ] 数据中台设计方案

**Comment by linziyang1106** [comment]
- [ ] 数据中台镜像上传缺陷

**Comment by linziyang1106** [comment]
- [ ] 镜像上传缺陷
- [ ] 34环境还原

crypto
- [ ] 调研oxygen（去年融了4500w）（看下合约代码，与别的defi有什么不同）
- [ ] solidity

**Comment by linziyang1106** [comment]
- [ ] 员工中心需求整理
- [ ] 数据接入指标计算

**Comment by linziyang1106** [comment]
- [ ] redissonclient研究
- [ ] 滨江示范区支持

**Comment by linziyang1106** [comment]
- [ ] 质量包计算模板
- [ ] 同事书籍学习分享
   1. 通用源码指导
   2. mysql是怎样运行的
   3. [手撸spring](https://bugstack.cn/md/spring/develop-spring/2021-05-16-%E7%AC%AC1%E7%AB%A0%EF%BC%9A%E5%BC%80%E7%AF%87%E4%BB%8B%E7%BB%8D%EF%BC%8C%E6%89%8B%E5%86%99Spring%E8%83%BD%E7%BB%99%E4%BD%A0%E5%B8%A6%E6%9D%A5%E4%BB%80%E4%B9%88%EF%BC%9F.html)

**Comment by linziyang1106** [comment]
- [ ] 修复github action
- [ ] 计算异常消失平均值

**Comment by linziyang1106** [comment]
- [ ] 测试质量包
- [ ] 看xxl-job

**Comment by linziyang1106** [comment]
- [ ] 酸奶
- [ ] 奥利奥

**Comment by linziyang1106** [comment]
- [ ] 延迟查询接口修改
- [ ] 打扫房间
- [ ] twitter推广 hashtag
- [ ] js ，module

**Comment by linziyang1106** [comment]
- [ ] 香菜
- [ ] 醋
- [ ] 香油
- [ ] 包菜
- [ ] 五花肉

**Comment by linziyang1106** [comment]
- [ ] b+树
- [ ] MP树
- [ ] 测试质量包
- [ ] apifox接口

**Comment by linziyang1106** [comment]
- [ ] itp-prod-baseline查看问题
- [ ] 测试容器多数据源

**Comment by linziyang1106** [comment]
- [ ] 分布式事务seata预研
- [ ] 多数据源不能切换的问题（事务注解）

**Comment by linziyang1106** [comment]
- [ ] os测试缺陷解决
- [ ] 数据质量 es数据导出链路
- [ ] 质量包修改，上传

**Comment by linziyang1106** [comment]
- [ ] 算法容器测试
- [ ] 大脑数据查询、链路延迟查询接口

**Comment by linziyang1106** [comment]
- [ ] 转换包的时间戳格式换为毫秒级
- [ ] 数据源创建缺陷修复

**Comment by linziyang1106** [comment]
- [ ] simple solidity

**Comment by linziyang1106** [comment]
- [ ] Redis的使用场景
- [ ] RedisTemplate源码
---
- [ ] 链路日志改造文档

**Comment by linziyang1106** [comment]
- [ ] Sqlite 学习

**Comment by linziyang1106** [comment]
- [ ] notion
- [ ] typora
- [ ] node
- [ ] vscode
- [ ] termius
- [ ] wps
- [ ] python3

**Comment by linziyang1106** [comment]
- [ ] 算法运行管理平台 抽取公共配置到yml

---
- [ ] 手套
- [ ] 洗碗布
- [ ] 水饺

**Comment by linziyang1106** [comment]
- [ ] 员工中心新需求评审
- [ ] 链路日志改造、测试

**Comment by linziyang1106** [comment]
- [ ] 整理笔记
- [ ] WTFSOL学习到30.trycatch
- [ ] 完成zombie一节

**Comment by linziyang1106** [comment]
- [ ] 改datahub、jdbc插件
- [ ] 链路日志交接
- [ ] es数据查询文档
- [ ] es查询延时
- [ ] 数据质量

**Comment by linziyang1106** [comment]
- [ ] 卡口过车转换包更新
- [ ] 设计文档
- [ ] h2特性

**Comment by linziyang1106** [comment]
- [ ] OSS 部署静态页面
- [ ] zombie编写

**Comment by linziyang1106** [comment]
- [ ] 如何利用nounce覆盖 transaction

**Comment by linziyang1106** [comment]
- [ ] alchemy roadmap
- [ ] week1

**Comment by ISheepp** [comment]
- [ ] react和next

**Comment by ISheepp** [comment]
- [ ] nextjs example
- [ ] contract test

**Comment by ISheepp** [comment]
- [ ] 算法容器 h2 改造
- [ ] WTF 复习 & road to web3 week5

**Comment by ISheepp** [comment]
- [ ] 椭圆曲线算法、对称/非对称加密、签名

**Comment by ISheepp** [comment]
- [ ] 小站算法容器 新需求：批量下载、批量删除日志、sync公用配置
- [ ] 检测包sdk，
- [ ] 算法
- [ ] wtf solidity

**Comment by ISheepp** [comment]
- [ ] 整理房间
- [ ] aave借贷分析

**Comment by ISheepp** [comment]
- [ ] 测试第三包引入是否报错（classloader）
- [ ] 前端资源
- [ ] 日志过滤归集功能

**Comment by ISheepp** [comment]
- [ ] 合并代码
- [ ] 算法日志

**Comment by ISheepp** [comment]
- [ ] 工程化部署
   - tar包上传 测试镜像是否能启动
- [ ] 复现日志打印的情况

**Comment by ISheepp** [comment]
- [ ] 小站算法容器缺陷
- [ ] 平台算法容器打包

**Comment by ISheepp** [comment]
- [ ] 开发future

**Comment by ISheepp** [comment]
- [ ] 算法容器同步，看代码
- [ ] 算法中台升级问题

**Comment by ISheepp** [comment]
- [ ] 下发算法包，一同上传依赖
- [ ] 算法仓库列表展示，只展示最新版本的包，下拉展示同一code的所有版本
- [ ] PIPE 改为DASH

**Comment by ISheepp** [comment]
- [ ] 赋能中心bug
- [ ] 代码合并（改版小站merge master）

**Comment by ISheepp** [comment]
- [ ] 修改算法中台调用的API
